# Generated by Django 5.1.3 on 2024-12-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pattern", "0002_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="yarn_type",
        ),
        migrations.AddField(
            model_name="project",
            name="yarn_type",
            field=models.ManyToManyField(
                related_name="projects", to="pattern.yarntype"
            ),
        ),
    ]
