# Generated by Django 5.1.3 on 2024-12-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="author",
            new_name="user",
        ),
    ]
