# Generated by Django 5.1.3 on 2024-12-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_yarn_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="time_spent",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Hours spent on project",
                max_digits=5,
                null=True,
            ),
        ),
    ]
