# Generated by Django 5.1.3 on 2024-12-23 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pattern", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pattern",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patterns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pattern",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="patterns", to="pattern.category"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="pattern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="pattern.pattern",
            ),
        ),
        migrations.AddField(
            model_name="pattern",
            name="tag",
            field=models.ManyToManyField(to="pattern.patterntag"),
        ),
        migrations.AddField(
            model_name="pattern",
            name="yarn_type",
            field=models.ManyToManyField(
                blank=True, related_name="patterns", to="pattern.yarntype"
            ),
        ),
    ]
